### ISSUE TITLE
rules wildcard

### ISSUE THREAD

**Issue by noraj** [ScriptSathi/HashKitty#14]
there is a wildcard for wordlists but not for rules

![image](https://github.com/ScriptSathi/HashKitty/assets/16578570/6e460bd0-c330-4823-8c5c-b3c5889eeaf0)

on the CLI one can do both `/opt/wordlists/* -r /opt/rules/*`

**Comment by noraj** [comment]
PS: we can add them one by one but this is tedious

**Comment by tdaudi** [comment]
This is fix with this [commit](https://github.com/ScriptSathi/HashKitty/commit/7a071fbaaf89fa21b8e917f9f0147bbd7d7193bc)

I close the issue
