### ISSUE TITLE
adding rules in a template enhancements

### ISSUE THREAD

**Issue by noraj** [ScriptSathi/HashKitty#15]
When adding rules in a template:

1. The list should show all ruels excepts the ones already added
2. Fix the CSS, adding a scrollbar rather than an overflowing field

![image](https://github.com/ScriptSathi/HashKitty/assets/16578570/0acb4e4c-c09c-413c-bbfe-368041e04c1e)

**Comment by tdaudi** [comment]
I do not find a very beautiful way to correct this. So as it extends i simply put an "overflow: scroll" when it's too big. But this is not very pretty ...

It's in this [commit](https://github.com/ScriptSathi/HashKitty/commit/2500ad4c5cf7c3c4d1872a7decf2129caf9725b4)

I close this issue as it is fixed
