### ISSUE TITLE
template not displayed

### ISSUE THREAD

**Issue by noraj** [ScriptSathi/HashKitty#16]
I added a template, I have a notification saying it was added successfully but the new template is not listed even after refreshing with cache cleaning.

![image](https://github.com/ScriptSathi/HashKitty/assets/16578570/362ee6b7-f850-42a7-b22e-efd6fe57361c)

**Comment by tdaudi** [comment]
```
QueryFailedError: Data too long for column 'rule_name' at row 1
```
The error occured because rules are not parsed correctly into the database.
I'll fix this

**Comment by tdaudi** [comment]
Problem solved with the [commit](https://github.com/ScriptSathi/HashKitty/commit/7a071fbaaf89fa21b8e917f9f0147bbd7d7193bc)

I close the issue
